### ISSUE TITLE
Doesn't work now?

### ISSUE THREAD

**Issue by 4ndrey** [NicolasRitouet/deployd-heroku-demo#9]
Log from heroku attached:

2017-03-12T04:29:34.684675+00:00 app[web.1]: Unhandled rejection TypeError: Cannot read property 'insert' of undefined
2017-03-12T04:29:34.684699+00:00 app[web.1]:     at /app/node_modules/deployd/lib/db.js:262:8
2017-03-12T04:29:34.684700+00:00 app[web.1]:     at /app/node_modules/deployd/lib/db.js:155:12
2017-03-12T04:29:34.684702+00:00 app[web.1]:     at runCallback (timers.js:651:20)
2017-03-12T04:29:34.684702+00:00 app[web.1]:     at tryOnImmediate (timers.js:624:5)
2017-03-12T04:29:34.684703+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-03-12T04:29:34.684705+00:00 app[web.1]: From previous event:
2017-03-12T04:29:34.684705+00:00 app[web.1]:     at collection (/app/node_modules/deployd/lib/db.js:154:11)
2017-03-12T04:29:34.684706+00:00 app[web.1]:     at SessionStore.Store.insert (/app/node_modules/deployd/lib/db.js:261:3)
2017-03-12T04:29:34.684707+00:00 app[web.1]:     at SessionStore.createSession (/app/node_modules/deployd/lib/session.js:110:10)
2017-03-12T04:29:34.684708+00:00 app[web.1]:     at /app/node_modules/deployd/lib/attach.js:92:23
2017-03-12T04:29:34.684709+00:00 app[web.1]:     at /app/node_modules/deployd/lib/util/http.js:64:9
2017-03-12T04:29:34.684709+00:00 app[web.1]:     at /app/node_modules/corser/lib/corser.js:99:13
2017-03-12T04:29:34.684710+00:00 app[web.1]:     at exports.setup (/app/node_modules/deployd/lib/util/http.js:24:3)
2017-03-12T04:29:34.684711+00:00 app[web.1]:     at handleRequest (/app/node_modules/deployd/lib/attach.js:89:5)
2017-03-12T04:29:34.684711+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-03-12T04:29:34.684712+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2017-03-12T04:29:34.684713+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7
2017-03-12T04:29:34.684713+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2017-03-12T04:29:34.684714+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2017-03-12T04:29:34.684714+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
2017-03-12T04:29:34.684715+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-03-12T04:29:34.684716+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2017-03-12T04:29:34.684717+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7
2017-03-12T04:29:34.684717+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2017-03-12T04:29:34.684718+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2017-03-12T04:30:04.652202+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=immense-thicket-85459.herokuapp.com request_id=04e42a3c-af94-4d2b-91b8-6741cdea010a fwd="5.79.156.244" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https

**Comment by archaistvolts** [comment]
I had a similar error when my mongo connection string wasn't set properly and the connection was failing.  You have to create a MONGOHQ_URL or MONGOLAB_URI config var in your app settings at the heroku dashboard that gets read in the server.js file.  Mine is a MONGOHQ_URL and it looks like this: `mongodb://<dbuser>:<dbpassword>@<host>:<port>/<db>`.  Good luck.
